### ISSUE TITLE
Manually Provide Desired Permissions?

### ISSUE THREAD

**Issue by Sn3akyP3t3** [joaomgcd/Tasker-Permissions#10]
Any chance some means of adding optional permissions sections can be added to the app via something like a YAML file?  This would make adding perms for apps like Termux a little easier.  https://github.com/termux/termux-tasker#comtermuxpermissionrun_command-permission-mandatory

**Comment by GitklcHub** [comment]
Auto-Merge

**Comment by Sn3akyP3t3** [comment]
Turns out this probably isn't such a good request.  For one it doesn't help solve the issue that I initially requested.  Another is that is likely would lead to an unnecessary vulnerability.  At worst it could give too much power to the user which could then move forward and shoot one's own foot.
