### ISSUE TITLE
Using over Wifi

### ISSUE THREAD

**Issue by AliceSippe** [joaomgcd/Tasker-Permissions#11]
Hi! 
Cant i use the app in adb over wifi mode? 

I cant connect my device using cable so i always adb over wifi on folder 5188 but the app cant find my device. 

ty!

**Comment by joaomgcd** [comment]
Yes, you can connect via WiFi but you have to do Wifi Pairing first in Android Settings. Did you try that? You would need Android Studio for that though...

**Comment by AliceSippe** [comment]
Ty João! 
I did it... i was using an older version of ADB. =( 
I am sorry for taking your time! 
btw: really good apps! i have almost all in my other account =) Nice job!

**Comment by joaomgcd** [comment]
Great! :) Glad it works! Thank you!
