### ISSUE TITLE
Feature Request: Add AutoTools

### ISSUE THREAD

**Issue by marcelser** [joaomgcd/Tasker-Permissions#12]
Hi,

The Tasker Permissions helper is a real helper especially if settings up a fresh device you have to collect all over the place the permissions for Tasker, Join, AutoInput, AutoTools, etc.

What I'm missing currently is AutoTools and it's 2 permissions WRITE_SECURE_SETTINGS and CHANGE_CONFIGURATION.

Can you please add AutoTools to Tasker-Permissions?

Thanks very much. Apart from that maybe some short incustructions that you first have to start ADB and connect the device before you can use Tasker-Permissions.

But thanks a lot for this great app, I had a new Galaxy S21 and it was missing still a lot of permissions for Taskter & AutoInput obviously that I didn't know about.

**Comment by joaomgcd** [comment]
Hi! The app does already include AutoTools  and the WRITE_SECURE_SETTINGS permission. (You're right that it doesn't have the CHANGE_CONFIGURATION permission yet though). Are you sure you're using the [latest release](https://github.com/joaomgcd/Tasker-Permissions/releases/tag/v0.2.0)?

**Comment by marcelser** [comment]
No, I think I used 1.1, sorry bothering you but you should add the missing auto tools permission
