### ISSUE TITLE
this app screwed up everything

### ISSUE THREAD

**Issue by degarb** [joaomgcd/Tasker-Permissions#18]
For some reason, after running tasker permissions, it screwed up everything, and now tasker has lost accessibility (although android says it has accessibility).  After running tasker permissions, I also lost autotools ability (and tasker) ability to change location and wifi.

I need a full list of adb commands, I am not going to run this progam again. 

I first did all the adb  command that google told me to.  Then I ran tasker tools and didn't see (no glasses on) that I was actually revoking permissions.   Then, I saw what I had done, ran the program, making sure I was enabling all the permissions, which clearly didn't work.

These are LG8 phones (no way via the gui to turn on battery saving location, which breaks location for me, as accurate location is a non starter for me, since I need as long of battery life as possible and every hour, every minute counts. 

So, please let me know how to manually adb the accessibility permission for tasker and all other permissions.

**Comment by joaomgcd** [comment]
Hi. When you use an action that needs a certain permission you'll get a guide telling you what command you need to run to enable that specific permission. That command is exactly the same as the command ran by the helper app, so running a command manually would have the same effect of running it through the helper app. I would recommend you uninstall/re-install Tasker so you can start over.

Hope this helps!
