### ISSUE TITLE
“com.joaomgcd.taskerpermissions” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by kunal60** [joaomgcd/Tasker-Permissions#19]
On macos:
<img width="256" alt="image" src="https://user-images.githubusercontent.com/31628126/205447565-29068a82-9ffc-424a-a527-ddafe6f1bb4d.png">

**Comment by joaomgcd** [comment]
HHmm. Do you know exactly what needs to be updated about it? :P

**Comment by stacksjb** [comment]
This is expected on Mac, as it is not developer signed. The way to fix this would be to get a developer signing certificate (but probably not likely to happen, as that requires being a member of the Apple Developer Program)

To workaround, Click "Show in Finder," then right/control-click and select "Open". This will give you  a different box that will allow you to click "Open Anyway"

You could also manually remove the quarantine attribute with sudo xattr -r -d com.apple.quarantine <path/to/file> but you shouldn't need to do that once you have opened it succesfully.

**Comment by stacksjb** [comment]
(This issue can probably be closed)
