### ISSUE TITLE
help me solve this issue

### ISSUE THREAD

**Issue by tarbear123** [joaomgcd/Tasker-Permissions#2]
when i try to grant permittion, i get this error screen
![image](https://user-images.githubusercontent.com/38800609/138527428-973223d6-a9b4-4f4b-bd8b-a40f25ea4d6f.png)

**Comment by Fireeyeeian** [comment]
I got the app but I still get this error. oneplus launcher keeps setting itself as default and I want to enforce setting nova as default.
