### ISSUE TITLE
Need to re-enable USB Debugging

### ISSUE THREAD

**Issue by stacksjb** [joaomgcd/Tasker-Permissions#21]
Hello,

I had issues using this with my OnePlus - I had to enable the "Disable Permissions Monitoring" option, however it doesn't take effect until you disable and re-enable USB Debugging and reconnect.

Please update the error message to specifically note to disable and re-enable USB Debugging after the options have been selected.

**Comment by joaomgcd** [comment]
Ok, done. Added that note which will be shown in the next release :) Thanks!
