### ISSUE TITLE
Errors on Write Secure Settings and Join permissions

### ISSUE THREAD

**Issue by Cnote43** [joaomgcd/Tasker-Permissions#27]
I've successfully use this permissions app in the past. Now when I run it, I get the following error for Write Secure Settings (for Tasker Settings):

![image](https://github.com/joaomgcd/Tasker-Permissions/assets/16570699/34e3d879-570d-4d73-ab20-f099e53de9e6)

and I get the following error for the join permissions:

`Error: Error: No UID for com.joaocmgcd.join in user o`

Tasker, AutoInput, AutoTools and AutoWear all worked.

Computer: Windows 10
Phone: Android 13, LineageOS 20

I'm probably missing something simple, but I've checked and tried everything multiple times and always get the same results.

**Comment by joaomgcd** [comment]
Did you install the latest Tasker Settings from here? https://github.com/joaomgcd/TaskerSettings/releases

**Comment by Cnote43** [comment]
Installing the latest Tasker Settings fixed the Write Secure Settings Error. Thank you!

I still get the `Error: Error: No UID for com.joaocmgcd.join in user o` for the Join permissions.

**Comment by joaomgcd** [comment]
Hhmm, and you're sure that Join is installed normally on the device? 😅

**Comment by Cnote43** [comment]
Wow. I've used Tasker for years and didn't know that Join existed. I thought it was just a certain set of Android permissions. Now I know. Thanks!

**Comment by joaomgcd** [comment]
Great! :) Glad you got it!
