### ISSUE TITLE
Tasker Settings Error

### ISSUE THREAD

**Issue by Juxto2010** [joaomgcd/Tasker-Permissions#28]
I am not sure if this error even matters since all other permissions are turned on just fine. I get this error when trying to grant permission in the Tasker Settings tab.

![Screenshot 2023-07-13 175903](https://github.com/joaomgcd/Tasker-Permissions/assets/99722883/49249b8d-387a-4b14-9138-4d5511ba8ba4)

![Screenshot 2023-07-13 175234](https://github.com/joaomgcd/Tasker-Permissions/assets/99722883/1445f496-6ba0-4e35-9360-c815e39ff638)

**Comment by joaomgcd** [comment]
You need to install a more up to date version of [Tasker Settings](https://github.com/joaomgcd/TaskerSettings/releases) :)

**Comment by Juxto2010** [comment]
I'm confused. I am downloading it from the play store. The version I see seems to be old. Here is a screenshot of the play store app description page that I am installing. Is there another location to download an up to date version?![Screenshot_20230714_075126_Google Play Store.jpg](https://github.com/joaomgcd/Tasker-Permissions/assets/99722883/f9999789-ebc1-4639-9eae-d6857dd63c90)

Thanks for the reply and forgive my ignorance.

**Comment by joaomgcd** [comment]
I actually posted a link to the updated version in my previous reply 😅 Here it is again: https://github.com/joaomgcd/TaskerSettings/releases

Hope this helps!
