### ISSUE TITLE
This adb server's $ADB_VENDOR_KEYS is not set

### ISSUE THREAD

**Issue by BillyCroan** [joaomgcd/Tasker-Permissions#30]
when I click grant (any red grant button) I get a error message pop up:

> adb: device unauthorized.
> This adb server's $ADB_VENDOR_KEYS is not set
> Try 'adb kill-server' if that seems wrong.
> Otherwise check for a confirmation dialog on your device.

killing the adb server doesn't seem to help

Pixel 7, android 14, Build UQ1A.240105.004
Debian Bookworm, kernel up to date

I tried on cli and got a similar error:
$ adb shell
adb server version (40) doesn't match this client (41); killing...
* daemon started successfully
adb: device unauthorized.
This adb server's $ADB_VENDOR_KEYS is not set
Try 'adb kill-server' if that seems wrong.
Otherwise check for a confirmation dialog on your device.

**Comment by joaomgcd** [comment]
Did you enable developer options and USB debugging on your phone?

**Comment by BillyCroan** [comment]
Yep
![Screenshot_20240129-063653](https://github.com/joaomgcd/Tasker-Permissions/assets/37587/ba26d3ba-f51c-464f-afcd-6fd3c9a42719)

**Comment by joaomgcd** [comment]
Can you try toggling it off, clicking the "Revoke..." option, then turning it on again and see if a popup shows up asking you to accept the connection?

**Comment by BillyCroan** [comment]
I did that, but nothing in the linux app changed.  I was however able to use adb on the commandline to grant the permissions after doing that.  I got the expected "allow this key to debug" message on the phone, approved it, and sdb shell then worked without error.  So manual ADB from apt works.  just not this app.

I thought I might try to get you the app version number for debugging purposes:
bcroan@x360:~/.config/systemd/user$ com.joaomgcd.taskerpermissions -version
libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed
Running chmod chmod 755 /opt/com.joaomgcd.taskerpermissions/resources/app.asar/bin/linux/adb
chmod result {
  code: 1,
  out: '',
  error: "chmod: cannot access '/opt/com.joaomgcd.taskerpermissions/resources/app.asar/bin/linux/adb': Not a directory\n"
}
Running command line Server /opt/com.joaomgcd.taskerpermissions/bin/linux/adb devices -l
Command line result {
  code: 0,
  out: 'List of devices attached\n\n',
  error: "adb server version (41) doesn't match this client (40); killing...\n" +
    '* daemon started successfully\n'
}

but --version just threw that error.   Interesting...  I wonder what version the adb is that you include in your app...
so I ran:

bcroan@x360:~/.config/systemd/user$ /opt/com.joaomgcd.taskerpermissions/resources/app.asar/bin/linux/adb --version
bash: /opt/com.joaomgcd.taskerpermissions/resources/app.asar/bin/linux/adb: Not a directory

What???

bcroan@x360:~/.config/systemd/user$ /opt/com.joaomgcd.taskerpermissions/resources/app.asar/bin/linux/adb 
bash: /opt/com.joaomgcd.taskerpermissions/resources/app.asar/bin/linux/adb: Not a directory
bcroan@x360:~/.config/systemd/user$ file /opt/com.joaomgcd.taskerpermissions/resources/app.asar/bin/linux/adb 
/opt/com.joaomgcd.taskerpermissions/resources/app.asar/bin/linux/adb: cannot open `/opt/com.joaomgcd.taskerpermissions/resources/app.asar/bin/linux/adb' (Not a directory)
bcroan@x360:~/.config/systemd/user$ ls -l  /opt/com.joaomgcd.taskerpermissions/resources/app.asar/bin/linux/adb 
ls: cannot access '/opt/com.joaomgcd.taskerpermissions/resources/app.asar/bin/linux/adb': Not a directory
bcroan@x360:~/.config/systemd/user$ ls -l  /opt/com.joaomgcd.taskerpermissions/resources/
/opt/com.joaomgcd.taskerpermissions/resources/:
total 1060
-rw-r--r-- 1 root root 1085004 Jan 25  2022 app.asar
bcroan@x360:~/.config/systemd/user$ ls -l  /opt/com.joaomgcd.taskerpermissions/resources/app.asar
-rw-r--r-- 1 root root 1085004 Jan 25  2022 /opt/com.joaomgcd.taskerpermissions/resources/app.asar
bcroan@x360:~/.config/systemd/user$ /opt/com.joaomgcd.taskerpermissions/resources/app.asar
bash: /opt/com.joaomgcd.taskerpermissions/resources/app.asar: Permission denied
bcroan@x360:~/.config/systemd/user$ file /opt/com.joaomgcd.taskerpermissions/resources/app.asar
/opt/com.joaomgcd.taskerpermissions/resources/app.asar: Electron ASAR archive, header length: 2587 bytes
bcroan@x360:~/.config/systemd/user$ 

So the adb you use is extracted at runtime and deleted after?

if it helps:md5sum /opt/com.joaomgcd.taskerpermissions/com.joaomgcd.taskerpermissions 
09bb8add8b6dafd865d6df29c38f88cf  /opt/com.joaomgcd.taskerpermissions/com.joaomgcd.taskerpermissions

**Comment by BillyCroan** [comment]
That shell error is a bit misleading.

$ /opt/com.joaomgcd.taskerpermissions/resources/app.asar/bin/linux/adb --version

bash: /opt/com.joaomgcd.taskerpermissions/resources/app.asar/bin/linux/adb: Not a directory

I tried to run adb --version.  and bash told me that's not a directory.  I believe "not a directory" applies to any one of the dirs in the path as I typed it.  Indeed app.asar, is not a directory.  it's a file for me.  But then why is it used as if it was a directory when I run:

com.joaomgcd.taskerpermissions -version

When you run "com.joaomgcd.taskerpermissions -version" do you see an error message?

**Comment by joaomgcd** [comment]
Where exactly would I run that command? In what folder?

**Comment by jeroenvermunt** [comment]
I am getting this error as well on linux after it seemed to work previously (got to a different error though)

on linux "com.joaomgcd.taskerpermissions -version" can be run in the terminal in any folder. I get this error message:

`chmod: cannot access '/opt/com.joaomgcd.taskerpermissions/resources/app.asar/bin/linux/adb': Not a directory\n`
