### ISSUE TITLE
Suggestion: include option to install TaskerSettings

### ISSUE THREAD

**Issue by beer-matt** [joaomgcd/Tasker-Permissions#31]
Would be useful if this app automated download of latest version of [TaskerSettings](https://github.com/joaomgcd/TaskerSettings) apk, then perform install (using adb install --bypass-low-target-sdk-block if necessary for Android 14+).

**Comment by joaomgcd** [comment]
Added, thanks! Are you maybe able to test this from code? Or do you need the build?

**Comment by beer-matt** [comment]
Thanks @joaomgcd; unfortunately I'm not going to be able to test today.. To be able to test from code what would I need (on Windows) - Node installed?
Any chance you could also take a look at [issue 32](https://github.com/joaomgcd/Tasker-Permissions/issues/32) too, hopefully also not too difficult to add (but would make life simpler for ADB over Wifi)?
