### ISSUE TITLE
Tasker accessibility

### ISSUE THREAD

**Issue by Lala1976** [joaomgcd/Tasker-Permissions#33]
I setup tasker on my head unit ,android 13. Everything works fine, also when i reboot tasker works, but when i turn of the head unit for a minute the accessibility is disabled. I ran the adb line to always turn on accessibility ,but didn't work.
Is there anything i can do?

**Comment by joaomgcd** [comment]
Did you try the option in Tasker Preferences to KEEP ACCESSIBILITY RUNNING?

**Comment by Lala1976** [comment]
Yes it works now.
Didn't know to go back to KEEP ACCESSIBILITY RUNNING for ticking Tasker after i ran the ADB line.
After I did that everything works.
Thanks

**Comment by joaomgcd** [comment]
Great! :) Glad it works!
