### ISSUE TITLE
ADB Vender Key not set

### ISSUE THREAD

**Issue by Spencer-Laframboise** [joaomgcd/Tasker-Permissions#34]
Hi! I recently got a pixel 7a and have had issues setting up my tasks again, in attempting to set up tasker on my device I am attempting to allow all prompts, but in doing so i get this error and am unsure what to do. Please help!

error: device unauthorized.
This adb server's $ADB_Vendor_Keys is not set
Try 'adb kill-server' if that seems wrong.
Otherwise check for a confirmation dialog on your device.

**Comment by clickwithclark** [comment]
![image](https://github.com/joaomgcd/Tasker-Permissions/assets/20617584/f3b15e65-baf2-45a9-a7bc-3556f78531d8)

![image](https://github.com/joaomgcd/Tasker-Permissions/assets/20617584/4d7af788-bf93-47df-a5c5-7873806f8f6d)


I would like to point out some stuff that helped me, I had to specifically select USB tethering and only then I was prompted on my phone to grant permission then everything went smoothly when I pressed restart button which also didn't immediately look like a button to me. Hope it helps someone

**Comment by joaomgcd** [comment]
Thanks for the extra info!
