### ISSUE TITLE
Tasker permissions portable fails to open

### ISSUE THREAD

**Issue by Redkitt3n14** [joaomgcd/Tasker-Permissions#8]
![Screenshot 2022-02-04 183956](https://user-images.githubusercontent.com/69162335/152584792-2fcfb298-0788-4564-8a50-10eff788ad87.png)

**Comment by jbd7** [comment]
@joaomgcd I just downloaded the Windows EXE and see the same error, on Windows 8.1, running the exe as Administrator. Same line numbers.

**Comment by jbd7** [comment]
@joaomgcd FYI, when this error happened, I had adb locally listening to Android connected via USB. After disconnecting the phone, restarting tasker_permissions_portable.exe launched correctly. The permissions were eventually granted via the EXE.
